django_demo/blog/urls.py
from django.conf.urls import url

from .views import site_views, user_views, post_views

app_name = 'blog'
urlpatterns = [
    url(r'^$', site_views.index, name='index'),
    url(r'^contact/$', site_views.contact, name='contact'),
    url(r'^contact/question/$', site_views.new_questions, name='new_question'),
    url(r'^contact/question/(?P<question_id>[0-9]+)/hide/$', site_views.hide_question, name='hide_question'),

    url(r'^post/$', post_views.post_create, name='create'),
    url(r'^post/(?P<post_id>[0-9]+)/$', post_views.post_detail, name='detail'),
    url(r'^post/(?P<post_id>[0-9]+)/edit/$', post_views.post_edit, name='edit'),
    url(r'^post/(?P<post_id>[0-9]+)/delete/$', post_views.post_delete, name='delete'),
    url(r'^post/(?P<post_id>[0-9]+)/removeheaderimage/$', post_views.post_remove_header_image, name='remove_header'),
    url(r'^post/(?P<post_id>[0-9]+)/comment/$', post_views.post_comment, name='post_comment'),
    url(r'^post/comment/(?P<comment_id>[0-9]+)/hide/$', post_views.post_comment_hide, name='post_comment_hide'),

    url(r'^post/(?P<post_id>[0-9]+)/publish/$', post_views.publish_post, name='post_publish'),

    url(r'^post/(?P<post_id>[0-9]+)/block/$', post_views.block_create, name='block_create'),
    url(r'^post/(?P<post_id>[0-9]+)/block/save/$', post_views.block_save, name='block_save'),
    url(r'^post/(?P<post_id>[0-9]+)/block/delete/$', post_views.block_delete, name='block_delete'),

    url(r'^user/(?P<user_id>[0-9]+)/$', user_views.user_detail, name='user'),
    url(r'^login/$', user_views.user_login, name='login'),
    url(r'^logout/$', user_views.user_logout, name='logout'),
    url(r'^registration/$', user_views.user_registration, name='registration'),
    url(r'^user/reset/$', user_views.change_password_user, name='change_password'),
    url(r'^user/$', user_views.user_profile, name='profile'),
]

django_demo/django_demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls')),
    url(r'^vue/', include('vue_js.urls')),
]

django_demo/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.utils import timezone


class Feedback(models.Model):
    name = models.CharField(max_length=50, help_text='Ваше имя')
    email = models.EmailField(help_text='Ваш email')
    question = models.CharField(max_length=1500, help_text='Вопрос')
    created_at = models.DateTimeField()
    is_read = models.BooleanField(default=False)
    user_ip = models.CharField(max_length=50)

    @classmethod
    def get_valid_questions(cls):
        return cls.objects.filter(is_read=False)

    @classmethod
    def hide_question(cls, q_id: int):
        question = cls.objects.get(pk=q_id)
        question.is_read = True
        question.save()


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, null=True)
    post_text = models.CharField(max_length=5000, null=True)
    created_at = models.DateTimeField()
    is_removed = models.BooleanField(default=False)
    is_published = models.BooleanField(default=True)

    @classmethod
    def get_post_or_create(cls, user_id: int):
        try:
            post = cls.objects.get(user_id=user_id, is_published=False, is_removed=False)
        except cls.DoesNotExist:
            post = cls(user_id=user_id, is_published=False, created_at=timezone.now())
            post.save()
        return post

    @classmethod
    def get_all_active_posts(cls):
        return cls.objects.filter(is_removed=False, is_published=True).order_by('-created_at')

    @classmethod
    def get_post_or_404(cls, post_id: int):
        return get_object_or_404(cls, pk=post_id, is_removed=False)

    def get_valid_comments(self):
        return PostComment.get_valid_comments(self.id)

    def get_all_blocks(self):
        return PostBlock.get_all_valid_blocks(self.id).order_by('pk')

    def get_unpublished_blocks(self):
        return PostBlock.get_unpublished_blocks(self.id).order_by('pk')

    def publish_post(self):
        self.is_published = True
        self.save()

    def remove_post(self):
        self.is_removed = True
        self.save()

    def have_post_image(self):
        return self.postfile_set.filter(file_type=PostFile.POST_IMAGE, is_removed=False).exists()

    def have_post_block(self):
        return self.postblock_set.filter(is_removed=False).exists()

    def get_post_image(self):
        return self.postfile_set.get(file_type=PostFile.POST_IMAGE, is_removed=False)

    def disable_post_image(self):
        post_image = self.get_post_image()
        if post_image is not None:
            post_image.is_removed = True
            post_image.save()

    def __str__(self):
        return "{id} | {author} : {title}".format(id=self.id, author=self.user.username, title=self.title)


class PostBlock(models.Model):
    BLOCK_IMAGE = 'block_image'
    BLOCK_CODE = 'block_code'
    BLOCK_TEXT = 'block_text'

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    block_type = models.CharField(max_length=50)
    storage = models.CharField(max_length=1500, null=True)
    is_removed = models.BooleanField(default=False)
    is_published = models.BooleanField(default=True)

    @staticmethod
    def get_all_valid_blocks(post_id: int):
        return PostBlock.objects.filter(post_id=post_id, is_removed=False, is_published=True)

    @staticmethod
    def get_block_or_404(block_id):
        return get_object_or_404(PostBlock, pk=block_id, is_removed=False)

    @staticmethod
    def get_unpublished_blocks(post_id: int):
        return PostBlock.objects.filter(post_id=post_id, is_removed=False, is_published=False)

    @staticmethod
    def publish_all_blocks(post_id):
        blocks = PostBlock.get_unpublished_blocks(post_id)
        blocks.update(is_published=True)

    def hide(self):
        self.is_removed = True
        self.save()


class PostFile(models.Model):
    POST_IMAGE = 'post_image'
    LOCAL_IMAGE = 'local_image'

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file_name = models.CharField(max_length=150)
    file_type = models.CharField(max_length=50)
    file_description = models.CharField(max_length=150, null=True, blank=True)
    is_removed = models.BooleanField(default=False)
    created_at = models.DateTimeField()

    def __str__(self):
        return "{id} | {type} : {filename}".format(id=self.id, type=self.file_type, filename=self.file_name)


class PostComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=500)
    created_at = models.DateTimeField()
    is_removed = models.BooleanField(default=False)

    @staticmethod
    def get_valid_comments(post_id=None):
        return PostComment.objects.filter(is_removed=False, post_id=post_id)

    def hide_comment(self):
        self.is_removed = True
        self.save()

    def __str__(self):
        return "{id} | {user} : {text}".format(id=self.id, user=self.user.username, text=self.comment_text)

django_demo/blog/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = models.Feedback
        fields = ['name', 'email', 'question']


class UserRegistrationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'username', 'password']


class UserLoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class PostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'post_text']


class PostFileForm(forms.Form):
    file = forms.ImageField()

django_demo/blog/views/post_views.py
from django.http import JsonResponse, HttpResponseForbidden, HttpResponseBadRequest
from django.shortcuts import resolve_url, render, get_object_or_404
from django.utils import timezone

from .. import constants, models, helpers, decorators, forms, services
from ..helpers import Request, File, Response


@decorators.group_require(constants.Group.REGULAR_USER)
def post_create(request):
    post = models.Post.get_post_or_create(request.user.id)
    form = forms.PostForm(instance=post)
    image_form = forms.PostFileForm()
    return render(request, 'blog/post_create.html', {'form': form, 'image_form': image_form})


@decorators.group_require(constants.Group.REGULAR_USER)
def post_edit(request, post_id: int):
    post = models.Post.get_post_or_404(post_id)
    form = forms.PostForm(instance=post)
    image_form = forms.PostFileForm()
    if request.user.id == post.user_id:
        return render(request, 'blog/post_edit.html', {'form': form, 'image_form': image_form})
    else:
        return HttpResponseForbidden()


@decorators.group_require(constants.Group.REGULAR_USER)
def post_delete(request, post_id: int):
    post = models.Post.get_post_or_404(post_id)
    if request.user.id == post.user_id:
        post.remove_post()
        return Response.go_home()
    else:
        return HttpResponseForbidden()


@decorators.group_require(constants.Group.REGULAR_USER)
def publish_post(request, post_id: int):
    post = get_object_or_404(models.Post, pk=post_id, is_removed=False)
    if request.user.id != post.user_id:
        return HttpResponseForbidden()
    models.PostBlock.publish_all_blocks(post_id)
    post.publish_post()
    return JsonResponse({'redirect': resolve_url('blog:detail', post_id)})


@decorators.group_require(constants.Group.REGULAR_USER)
def block_create(request, post_id: int):
    post = get_object_or_404(models.Post, pk=post_id, is_removed=False)
    if request.user.id != post.user_id:
        return HttpResponseForbidden()
    block = models.PostBlock(post_id=post_id, is_published=False)
    if request.POST.get('block_type') == models.PostBlock.BLOCK_CODE:
        block.block_type = models.PostBlock.BLOCK_CODE
    elif request.POST.get('block_type') == models.PostBlock.BLOCK_TEXT:
        block.block_type = models.PostBlock.BLOCK_TEXT
    elif request.POST.get('block_type') == models.PostBlock.BLOCK_IMAGE:
        block.block_type = models.PostBlock.BLOCK_IMAGE
    else:
        return HttpResponseBadRequest('Not valid block type')
    block.save()
    return JsonResponse({'block_id': block.id, 'block_type': block.block_type})


@decorators.group_require(constants.Group.REGULAR_USER)
def block_save(request, post_id: int):
    post = models.Post.get_post_or_404(post_id)
    if request.user.id != post.user_id:
        return HttpResponseForbidden()
    block_id = request.POST.get('block_id')
    block = models.PostBlock.objects.get(pk=block_id)
    block.storage = request.POST.get('value')
    block.save()
    return JsonResponse({'status': '200', 'block_id': block.id})


@decorators.group_require(constants.Group.REGULAR_USER)
def block_delete(request, post_id: int):
    post = models.Post.get_post_or_404(post_id)
    if request.user.id == post.user_id:
        block_id = request.POST.get('block_id')
        models.PostBlock.get_block_or_404(block_id).hide()
        return JsonResponse({'status': '200', 'block_id': block_id})
    else:
        return HttpResponseForbidden()


def post_detail(request, post_id: int):
    post = models.Post.get_post_or_404(post_id)
    return render(request, 'blog/post_detail.html', {'post': post})


@decorators.group_require(constants.Group.REGULAR_USER)
def post_remove_header_image(request, post_id: int):
    post = models.Post.get_post_or_404(post_id)
    post.disable_post_image()
    return Response.redirect('blog:edit', args=[post_id])


@decorators.group_require(constants.Group.REGULAR_USER)
def post_comment(request, post_id: int):
    if Request.is_post(request):
        comment_text = request.POST['post_comment']
        models.PostComment(post_id=post_id, comment_text=comment_text, created_at=timezone.now(),
                           user_id=request.user.id).save()
        return Response.redirect('blog:detail', args=[post_id])


@decorators.superuser_only
def post_comment_hide(request, comment_id: int):
    comment = get_object_or_404(models.PostComment, pk=comment_id)
    comment.hide_comment()
    return Response.redirect('blog:detail', args=[comment.post_id])

django_demo/blog/views/site_views.py
from django.contrib import messages
from django.shortcuts import render
from django.utils import timezone

from .. import constants, models, helpers, decorators, forms, services
from ..helpers import Response, Request


def index(request):
    posts = models.Post.get_all_active_posts()
    return render(request, 'blog/index.html', {'posts': posts})


def contact(request):
    if Request.is_post(request):
        form = forms.FeedbackForm(request.POST)
        if form.is_valid():
            model = form.save(commit=False)
            model.user_ip = Request.get_client_ip(request)
            model.created_at = timezone.now()
            model.save()
            messages.add_message(request, messages.INFO, 'Question sent to admin')
    else:
        form = forms.FeedbackForm()
    return render(request, 'blog/contact.html', {'form': form})


@decorators.superuser_only
def new_questions(request):
    questions = models.Feedback.get_valid_questions()
    return render(request, 'blog/questions.html', {'questions': questions})


@decorators.superuser_only
def hide_question(request, question_id: int):
    models.Feedback.hide_question(question_id)
    return Response.redirect('blog:new_question')

django_demo/blog/views/user_views.py
from django.contrib import auth, messages
from django.contrib.auth.models import User, Group
from django.shortcuts import render, get_object_or_404

from .. import constants, models, helpers, decorators, forms, services
from ..helpers import Request, Response


@decorators.guest_only
def user_login(request):
    if Request.is_post(request):
        username, password = Request.get_fields_request(request, 'username', 'password')
        user = auth.authenticate(username=username, password=password)
        if user is not None and user.is_active:
            auth.login(request, user)
            return Response.go_home()
    form = forms.UserLoginForm()
    return render(request, 'blog/user_login.html', {'form': form})


def user_logout(request):
    auth.logout(request)
    return Response.go_home()


@decorators.no_login_require
def user_registration(request):
    if Request.is_post(request):
        form = forms.UserRegistrationForm(request.POST)
        if form.is_valid():
            username, password, email = Request.get_fields_request(request, 'username', 'password', 'email')
            user = User.objects.create_user(username=username, password=password, email=email)
            user.groups.add(Group.objects.get(name=constants.Group.REGULAR_USER))
            auth.login(request, user)
            return Response.go_home()
        else:
            messages.add_message(request, messages.INFO, 'User: ' + request.POST['username'] + ' already exist')
    else:
        form = forms.UserRegistrationForm()
    return render(request, 'blog/user_registration.html', {'form': form})


def user_profile(request):
    return render(request, 'blog/user_profile.html')


def change_password_user(request):
    messages.add_message(request, messages.INFO, 'You can not change the password')
    return render(request, 'blog/reset_password.html')


def user_detail(request, user_id: int):
    user = get_object_or_404(User, pk=user_id)
    return render(request, 'blog/user_detail.html', {'user': user})

django_demo/blog/templates/blog/post/_block_for_post.html
{% load staticfiles %}
<div block_id="{{ block.id }}">
    <hr class="margin-bottom-10">
    <span class="label label-info margin-bottom-10">Type: {{ block.block_type }}</span>
    <span class="label label-pill label-danger margin-bottom-10 remove-block" block_id="{{ block.id }}">remove</span>
    <span class="label label-success margin-bottom-10 save-block" block_id="{{ block.id }}">save changes</span>
    {% if block.is_published %}
        {% if block.block_type == 'block_text' %}
            <div class="margin-top-10">{{ block.storage|linebreaks|urlize }}</div>
        {% elif block.block_type == 'block_image' %}
            <div class="blog-post margin-top-10">
                <div class="post-image">
                    <img src="{% static 'blog/user_files' %}/{{ block.storage }}">
                </div>
            </div>
        {% elif block.block_type == 'block_code' %}
            <pre class="margin-top-10">{{ block.storage }}</pre>
        {% endif %}
    {% else %}
        {% if block.block_type == 'block_text' %}
            {% include 'blog/post/_post_textarea.html' with block=block %}
        {% elif block.block_type == 'block_image' %}
            <div class="blog-post margin-top-10">
                <div class="post-image">
                    <img src="{% static 'blog/user_files' %}/{{ block.storage }}">
                </div>
            </div>
        {% elif block.block_type == 'block_code' %}
            {% include 'blog/post/_post_textarea.html' with block=block %}
        {% endif %}
    {% endif %}
</div>

django_demo/blog/templates/blog/post/_load_button.html
<div class="col-md-12 text-center">
    <a href="javascript:void(0)" id="load-more-post"
       class="load-more-button">Load</a>
    <div id="post-end-message"></div>
</div>

django_demo/blog/templates/blog/post/_post_block.html
{% load staticfiles %}
{% load blog_tags %}
<div class="col-md-12 blog-post">

    {% if post.have_post_image %}
        <div class="post-image">
            <a href="{% url 'blog:detail' post.id %}">
                <img src="{% static 'blog/user_files' %}/{{ post.get_post_image.file_name }}" alt="">
            </a>
        </div>
    {% endif %}

    <div class="post-title">
        <a href="{% url 'blog:detail' post.id %}"><h1>{{ post.title }}</h1></a>
    </div>
    <div class="post-info">
        <span>
            {{ post.created_at|date }} {{ post.created_at|time }} / by <a
                href="{% url 'blog:user' post.user.id %}">{{ post.user.username }}</a>
            {% if request.user.id == post.user_id %}
                (
                <a href="{% url 'blog:edit' post.id %}">Edit</a>
                /
                <a data-toggle="modal" href="#delete-post-modal-{{ post.id }}">Delete</a>
                <div class="modal fade" id="delete-post-modal-{{ post.id }}">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal"
                                        aria-hidden="true">&times;</button>
                                <h4 class="modal-title">Delete this post?</h4>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                <a href="{% url 'blog:delete' post.id %}" type="button"
                                   class="btn btn-danger">Delete</a>
                            </div>
                        </div>
                    </div>
                </div>
                )
            {% endif %}
        </span>
    </div>

    {% if truncatechars %}
        <p>{{ post.post_text|truncatechars_html:200|linebreaks|urlize }}</p>
        <a href="{% url 'blog:detail' post.id %}"
           class="button button-style button-anim fa fa-long-arrow-right"><span>Read More</span></a>
        <hr>
    {% else %}
        <div>
            <div class="form-group" id="post_blocks">
                {{ post.post_text|linebreaks|urlize }}
                {% for block in post.get_all_blocks %}
                    <hr>
                    {% if block.block_type == 'block_text' %}
                        {{ block.storage|linebreaks|urlize }}
                    {% elif block.block_type == 'block_image' %}
                        <div class="blog-post">
                            <div class="post-image">
                                <img src="{% static 'blog/user_files' %}/{{ block.storage }}">
                            </div>
                        </div>
                    {% elif block.block_type == 'block_code' %}
                        <pre>{{ block.storage }}</pre>
                    {% endif %}
                {% endfor %}
            </div>
        </div>
    {% endif %}

</div>

django_demo/blog/templates/blog/post/_post_comment_block.html
<div class="panel panel-default" style="border: 1px solid">
    <div class="panel-body">
        {{ comment.comment_text }}
    </div>
    <div class="panel-footer">
        {{ comment.created_at|date }} {{ comment.created_at|time }} / by <a
            href="{% url 'blog:user' comment.user_id %}" class="">{{ comment.user.username }}</a>
        {% if request.user.is_superuser %}
            (
            <a href="{% url 'blog:post_comment_hide' comment.id %}">Hide</a>
            )
        {% endif %}
    </div>
</div>

django_demo/blog/templates/blog/post/_post_comment_form.html
{% if request.user.is_authenticated %}
    <form action="{% url 'blog:post_comment' post.id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-lg-12" style="padding: 0px">
            <div class="input-group input-group-lg">
                <input type="text" class="form-control" required name="post_comment" placeholder="Comment this post">
                <span class="input-group-btn">
            <button class="btn btn-success" type="submit">Send</button>
        </span>
            </div>
        </div>
    </form>
{% else %}
    Add comment can only <a href="{% url 'blog:login' %}">authorized</a> users
{% endif %}

django_demo/blog/templates/blog/post/_post_form.html
{% load staticfiles %}
<form method="post" enctype="multipart/form-data" action="" id="form">

    {% csrf_token %}
    {% if form.instance.have_post_image %}
        <div class="col-md-12 blog-post">
            <div class="post-image">
                <img id="post_image" src="{% static 'blog/user_files' %}/{{ form.instance.get_post_image.file_name }}">
            </div>
        </div>
        <div class="col-sm-3 margin-top-10 padding-right-5" style="width: auto;">
            <div class="form-group margin-bottom-10">
                <label id="post_image_button" class="btn btn-success" for="post_image_input">
                    <i class="icon icon-reload"></i> Change post image header
                </label>
            </div>
        </div>
        <div class="col-sm-3 margin-top-10 padding-left-5 padding-right-5" style="width: auto;">
            <div class="form-group margin-bottom-10">
                <a href="{% url 'blog:remove_header' form.instance.id %}">
                    <label class="btn btn-danger">
                        <i class="icon-trash"></i> Remove post image header
                    </label>
                </a>
            </div>
        </div>
    {% else %}
        <div class="col-md-12 blog-post">
            <div class="post-image">
                <img id="post_image" src="">
            </div>
        </div>
        <div class="col-sm-3 margin-top-10 padding-right-5" style="width: auto;">
            <div class="form-group margin-bottom-10">
                <label id="post_image_button" class="btn btn-info" for="post_image_input">
                    <i class="icon icon-settings"></i> Add post image header
                </label>
            </div>
        </div>
    {% endif %}

    <a hidden><input type="file" name="{{ image_form.file.html_name }}" id="post_image_input"></a>

    <div class="col-sm-12" style="padding-left: 5px">
        <div class="col-sm-3 margin-top-10 padding-right-5" style="width: auto; padding-left: 10px">
            <div class="form-group margin-bottom-10">
                <a class="btn btn-primary" id="add_image_block_button">Add image block</a>
            </div>
        </div>
        <div class="col-sm-3 margin-top-10 padding-right-5" style="width: auto;">
            <div class="form-group margin-bottom-10">
                <a class="btn btn-primary" id="add_code_block_button">Add code block</a>
            </div>
        </div>
        <div class="col-sm-3 margin-top-10 padding-right-5" style="width: auto;">
            <div class="form-group margin-bottom-10">
                <a class="btn btn-primary" id="add_text_block_button">Add text block</a>
            </div>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="form-group">
            <input required type="text" id="{{ form.title.html_name }}"
                   name="{{ form.title.html_name }}" class="form-control" value="{% firstof form.title.value %}"
                   placeholder="{{ form.title.label }}" title="Post title">
        </div>
    </div>

    <div class="col-sm-12" title="Notice!">
        <div class="form-group">
            <div class="alert alert-info">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <strong>Notice:</strong> First block is always text
            </div>
        </div>
    </div>

    <div class="col-sm-12">
        <div class="form-group" id="post_blocks">
            <textarea required id="{{ form.post_text.html_name }}" name="{{ form.post_text.html_name }}"
                      class="form-control" rows="10" title="Post text, first block"
                      placeholder="{{ form.post_text.label }}">{% firstof form.post_text.value %}
            </textarea>
            {% if form.instance.have_post_block %}
                {% for block in form.instance.get_all_blocks %}
                    {% include 'blog/post/_block_for_post.html' with block=block %}
                {% endfor %}
                <hr>
                <div class="alert alert-info">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                    <strong>Below is unpublished blocks</strong>
                </div>
                {% for block in form.instance.get_unpublished_blocks %}
                    {% include 'blog/post/_block_for_post.html' with block=block %}
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <div class="text-center" id="send_form_button">
        <button type="button" class="load-more-button">Publish</button>
    </div>

</form>

django_demo/blog/templates/blog/post/_post_textarea.html
<textarea required block_id="{{ block.id }}"
          class="form-control margin-top-10" rows="10" title="Extend block: {{ block.block_type }}"
          placeholder="Extend block: {{ block.block_type }}">{% firstof block.storage %}
</textarea>