django_demo/blog/urls.py
from django.conf.urls import url

from .views import site_views, user_views, post_views

app_name = 'blog'
urlpatterns = [
    url(r'^$', site_views.index, name='index'),
    url(r'^contact/$', site_views.contact, name='contact'),
    url(r'^contact/question/$', site_views.new_questions, name='new_question'),
    url(r'^contact/question/(?P<question_id>[0-9]+)/hide/$', site_views.hide_question, name='hide_question'),

    url(r'^post/$', post_views.post_create, name='create'),
    url(r'^post/(?P<post_id>[0-9]+)/$', post_views.post_detail, name='detail'),
    url(r'^post/(?P<post_id>[0-9]+)/edit/$', post_views.post_edit, name='edit'),
    url(r'^post/(?P<post_id>[0-9]+)/delete/$', post_views.post_delete, name='delete'),
    url(r'^post/(?P<post_id>[0-9]+)/removeheaderimage/$', post_views.post_remove_header_image, name='remove_header'),
    url(r'^post/(?P<post_id>[0-9]+)/comment/$', post_views.post_comment, name='post_comment'),
    url(r'^post/comment/(?P<comment_id>[0-9]+)/hide/$', post_views.post_comment_hide, name='post_comment_hide'),

    url(r'^post/(?P<post_id>[0-9]+)/publish/$', post_views.publish_post, name='post_publish'),

    url(r'^post/(?P<post_id>[0-9]+)/block/$', post_views.block_create, name='block_create'),
    url(r'^post/(?P<post_id>[0-9]+)/block/save/$', post_views.block_save, name='block_save'),
    url(r'^post/(?P<post_id>[0-9]+)/block/delete/$', post_views.block_delete, name='block_delete'),

    url(r'^user/(?P<user_id>[0-9]+)/$', user_views.user_detail, name='user'),
    url(r'^login/$', user_views.user_login, name='login'),
    url(r'^logout/$', user_views.user_logout, name='logout'),
    url(r'^registration/$', user_views.user_registration, name='registration'),
    url(r'^user/reset/$', user_views.change_password_user, name='change_password'),
    url(r'^user/$', user_views.user_profile, name='profile'),
]

django_demo/django_demo/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls')),
    url(r'^vue/', include('vue_js.urls')),
]

django_demo/vue_js/urls.py
from django.conf.urls import url

from . import views

app_name = 'vue_js'
urlpatterns = [
    url(r'^$', views.Index.as_view(), name='index'),
]

django_demo/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.utils import timezone


class Feedback(models.Model):
    name = models.CharField(max_length=50, help_text='Ваше имя')
    email = models.EmailField(help_text='Ваш email')
    question = models.CharField(max_length=1500, help_text='Вопрос')
    created_at = models.DateTimeField()
    is_read = models.BooleanField(default=False)
    user_ip = models.CharField(max_length=50)

    @classmethod
    def get_valid_questions(cls):
        return cls.objects.filter(is_read=False)

    @classmethod
    def hide_question(cls, q_id: int):
        question = cls.objects.get(pk=q_id)
        question.is_read = True
        question.save()


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=50, null=True)
    post_text = models.CharField(max_length=5000, null=True)
    created_at = models.DateTimeField()
    is_removed = models.BooleanField(default=False)
    is_published = models.BooleanField(default=True)

    @classmethod
    def get_post_or_create(cls, user_id: int):
        try:
            post = cls.objects.get(user_id=user_id, is_published=False, is_removed=False)
        except cls.DoesNotExist:
            post = cls(user_id=user_id, is_published=False, created_at=timezone.now())
            post.save()
        return post

    @classmethod
    def get_all_active_posts(cls):
        return cls.objects.filter(is_removed=False, is_published=True).order_by('-created_at')

    @classmethod
    def get_post_or_404(cls, post_id: int):
        return get_object_or_404(cls, pk=post_id, is_removed=False)

    def get_valid_comments(self):
        return PostComment.get_valid_comments(self.id)

    def get_all_blocks(self):
        return PostBlock.get_all_valid_blocks(self.id).order_by('pk')

    def get_unpublished_blocks(self):
        return PostBlock.get_unpublished_blocks(self.id).order_by('pk')

    def publish_post(self):
        self.is_published = True
        self.save()

    def remove_post(self):
        self.is_removed = True
        self.save()

    def have_post_image(self):
        return self.postfile_set.filter(file_type=PostFile.POST_IMAGE, is_removed=False).exists()

    def have_post_block(self):
        return self.postblock_set.filter(is_removed=False).exists()

    def get_post_image(self):
        return self.postfile_set.get(file_type=PostFile.POST_IMAGE, is_removed=False)

    def disable_post_image(self):
        post_image = self.get_post_image()
        if post_image is not None:
            post_image.is_removed = True
            post_image.save()

    def __str__(self):
        return "{id} | {author} : {title}".format(id=self.id, author=self.user.username, title=self.title)


class PostBlock(models.Model):
    BLOCK_IMAGE = 'block_image'
    BLOCK_CODE = 'block_code'
    BLOCK_TEXT = 'block_text'

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    block_type = models.CharField(max_length=50)
    storage = models.CharField(max_length=1500, null=True)
    is_removed = models.BooleanField(default=False)
    is_published = models.BooleanField(default=True)

    @staticmethod
    def get_all_valid_blocks(post_id: int):
        return PostBlock.objects.filter(post_id=post_id, is_removed=False, is_published=True)

    @staticmethod
    def get_block_or_404(block_id):
        return get_object_or_404(PostBlock, pk=block_id, is_removed=False)

    @staticmethod
    def get_unpublished_blocks(post_id: int):
        return PostBlock.objects.filter(post_id=post_id, is_removed=False, is_published=False)

    @staticmethod
    def publish_all_blocks(post_id):
        blocks = PostBlock.get_unpublished_blocks(post_id)
        blocks.update(is_published=True)

    def hide(self):
        self.is_removed = True
        self.save()


class PostFile(models.Model):
    POST_IMAGE = 'post_image'
    LOCAL_IMAGE = 'local_image'

    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    file_name = models.CharField(max_length=150)
    file_type = models.CharField(max_length=50)
    file_description = models.CharField(max_length=150, null=True, blank=True)
    is_removed = models.BooleanField(default=False)
    created_at = models.DateTimeField()

    def __str__(self):
        return "{id} | {type} : {filename}".format(id=self.id, type=self.file_type, filename=self.file_name)


class PostComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=500)
    created_at = models.DateTimeField()
    is_removed = models.BooleanField(default=False)

    @staticmethod
    def get_valid_comments(post_id=None):
        return PostComment.objects.filter(is_removed=False, post_id=post_id)

    def hide_comment(self):
        self.is_removed = True
        self.save()

    def __str__(self):
        return "{id} | {user} : {text}".format(id=self.id, user=self.user.username, text=self.comment_text)

django_demo/blog/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models


class FeedbackForm(forms.ModelForm):
    class Meta:
        model = models.Feedback
        fields = ['name', 'email', 'question']


class UserRegistrationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'username', 'password']


class UserLoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class PostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title', 'post_text']


class PostFileForm(forms.Form):
    file = forms.ImageField()

django_demo/blog/views/post_views.py
from django.http import JsonResponse, HttpResponseForbidden, HttpResponseBadRequest
from django.shortcuts import resolve_url, render, get_object_or_404
from django.utils import timezone

from .. import constants, models, helpers, decorators, forms, services
from ..helpers import Request, File, Response


@decorators.group_require(constants.Group.REGULAR_USER)
def post_create(request):
    post = models.Post.get_post_or_create(request.user.id)
    form = forms.PostForm(instance=post)
    image_form = forms.PostFileForm()
    return render(request, 'blog/post_create.html', {'form': form, 'image_form': image_form})


@decorators.group_require(constants.Group.REGULAR_USER)
def post_edit(request, post_id: int):
    post = models.Post.get_post_or_404(post_id)
    form = forms.PostForm(instance=post)
    image_form = forms.PostFileForm()
    if request.user.id == post.user_id:
        return render(request, 'blog/post_edit.html', {'form': form, 'image_form': image_form})
    else:
        return HttpResponseForbidden()


@decorators.group_require(constants.Group.REGULAR_USER)
def post_delete(request, post_id: int):
    post = models.Post.get_post_or_404(post_id)
    if request.user.id == post.user_id:
        post.remove_post()
        return Response.go_home()
    else:
        return HttpResponseForbidden()


@decorators.group_require(constants.Group.REGULAR_USER)
def publish_post(request, post_id: int):
    post = get_object_or_404(models.Post, pk=post_id, is_removed=False)
    if request.user.id != post.user_id:
        return HttpResponseForbidden()
    models.PostBlock.publish_all_blocks(post_id)
    post.publish_post()
    return JsonResponse({'redirect': resolve_url('blog:detail', post_id)})


@decorators.group_require(constants.Group.REGULAR_USER)
def block_create(request, post_id: int):
    post = get_object_or_404(models.Post, pk=post_id, is_removed=False)
    if request.user.id != post.user_id:
        return HttpResponseForbidden()
    block = models.PostBlock(post_id=post_id, is_published=False)
    if request.POST.get('block_type') == models.PostBlock.BLOCK_CODE:
        block.block_type = models.PostBlock.BLOCK_CODE
    elif request.POST.get('block_type') == models.PostBlock.BLOCK_TEXT:
        block.block_type = models.PostBlock.BLOCK_TEXT
    elif request.POST.get('block_type') == models.PostBlock.BLOCK_IMAGE:
        block.block_type = models.PostBlock.BLOCK_IMAGE
    else:
        return HttpResponseBadRequest('Not valid block type')
    block.save()
    return JsonResponse({'block_id': block.id, 'block_type': block.block_type})


@decorators.group_require(constants.Group.REGULAR_USER)
def block_save(request, post_id: int):
    post = models.Post.get_post_or_404(post_id)
    if request.user.id != post.user_id:
        return HttpResponseForbidden()
    block_id = request.POST.get('block_id')
    block = models.PostBlock.objects.get(pk=block_id)
    block.storage = request.POST.get('value')
    block.save()
    return JsonResponse({'status': '200', 'block_id': block.id})


@decorators.group_require(constants.Group.REGULAR_USER)
def block_delete(request, post_id: int):
    post = models.Post.get_post_or_404(post_id)
    if request.user.id == post.user_id:
        block_id = request.POST.get('block_id')
        models.PostBlock.get_block_or_404(block_id).hide()
        return JsonResponse({'status': '200', 'block_id': block_id})
    else:
        return HttpResponseForbidden()


def post_detail(request, post_id: int):
    post = models.Post.get_post_or_404(post_id)
    return render(request, 'blog/post_detail.html', {'post': post})


@decorators.group_require(constants.Group.REGULAR_USER)
def post_remove_header_image(request, post_id: int):
    post = models.Post.get_post_or_404(post_id)
    post.disable_post_image()
    return Response.redirect('blog:edit', args=[post_id])


@decorators.group_require(constants.Group.REGULAR_USER)
def post_comment(request, post_id: int):
    if Request.is_post(request):
        comment_text = request.POST['post_comment']
        models.PostComment(post_id=post_id, comment_text=comment_text, created_at=timezone.now(),
                           user_id=request.user.id).save()
        return Response.redirect('blog:detail', args=[post_id])


@decorators.superuser_only
def post_comment_hide(request, comment_id: int):
    comment = get_object_or_404(models.PostComment, pk=comment_id)
    comment.hide_comment()
    return Response.redirect('blog:detail', args=[comment.post_id])

django_demo/blog/views/site_views.py
from django.contrib import messages
from django.shortcuts import render
from django.utils import timezone

from .. import constants, models, helpers, decorators, forms, services
from ..helpers import Response, Request


def index(request):
    posts = models.Post.get_all_active_posts()
    return render(request, 'blog/index.html', {'posts': posts})


def contact(request):
    if Request.is_post(request):
        form = forms.FeedbackForm(request.POST)
        if form.is_valid():
            model = form.save(commit=False)
            model.user_ip = Request.get_client_ip(request)
            model.created_at = timezone.now()
            model.save()
            messages.add_message(request, messages.INFO, 'Question sent to admin')
    else:
        form = forms.FeedbackForm()
    return render(request, 'blog/contact.html', {'form': form})


@decorators.superuser_only
def new_questions(request):
    questions = models.Feedback.get_valid_questions()
    return render(request, 'blog/questions.html', {'questions': questions})


@decorators.superuser_only
def hide_question(request, question_id: int):
    models.Feedback.hide_question(question_id)
    return Response.redirect('blog:new_question')

django_demo/blog/views/user_views.py
from django.contrib import auth, messages
from django.contrib.auth.models import User, Group
from django.shortcuts import render, get_object_or_404

from .. import constants, models, helpers, decorators, forms, services
from ..helpers import Request, Response


@decorators.guest_only
def user_login(request):
    if Request.is_post(request):
        username, password = Request.get_fields_request(request, 'username', 'password')
        user = auth.authenticate(username=username, password=password)
        if user is not None and user.is_active:
            auth.login(request, user)
            return Response.go_home()
    form = forms.UserLoginForm()
    return render(request, 'blog/user_login.html', {'form': form})


def user_logout(request):
    auth.logout(request)
    return Response.go_home()


@decorators.no_login_require
def user_registration(request):
    if Request.is_post(request):
        form = forms.UserRegistrationForm(request.POST)
        if form.is_valid():
            username, password, email = Request.get_fields_request(request, 'username', 'password', 'email')
            user = User.objects.create_user(username=username, password=password, email=email)
            user.groups.add(Group.objects.get(name=constants.Group.REGULAR_USER))
            auth.login(request, user)
            return Response.go_home()
        else:
            messages.add_message(request, messages.INFO, 'User: ' + request.POST['username'] + ' already exist')
    else:
        form = forms.UserRegistrationForm()
    return render(request, 'blog/user_registration.html', {'form': form})


def user_profile(request):
    return render(request, 'blog/user_profile.html')


def change_password_user(request):
    messages.add_message(request, messages.INFO, 'You can not change the password')
    return render(request, 'blog/reset_password.html')


def user_detail(request, user_id: int):
    user = get_object_or_404(User, pk=user_id)
    return render(request, 'blog/user_detail.html', {'user': user})

django_demo/blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
        <!-- Meta Tag -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">

        <!-- SEO -->
        {% block metatags %}
            <meta name="description" content="{% block meta_description %}150 words{% endblock meta_description %}">
            <meta name="author" content="{% block meta_author %}uipasta{% endblock meta_author %}">
        {% endblock metatags %}

        <title>{% block page_title %}ChernihV Blog{% endblock page_title %}</title>

        <link rel="shortcut icon" href="{% static 'blog/images/favicon/favicon.ico' %}">
        <link rel="apple-touch-icon" sizes="144x144" type="image/x-icon"
              href="{% static 'blog/images/favicon/apple-touch-icon.png' %}">

        {% block all_stylesheets %}
            {% block main_stylesheets %}
                <link rel="stylesheet" type="text/css" href="{% static 'blog/css/plugin.css' %}">
                <link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}">
                <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:400,300,500,600,700">
            {% endblock main_stylesheets %}
            {% block custom_stylesheets %}
            {% endblock custom_stylesheets %}
        {% endblock all_stylesheets %}

    {% endblock head %}
</head>

<body>
{% block body %}

    {% block body_utils_preloader %}
        <div class="preloader">
            <div class="rounder"></div>
        </div>
    {% endblock body_utils_preloader %}

    <div id="main">
        <div class="container">
            <div class="row">
                <div class="col-md-12 page-body">
                    <div class="row">

                        {% block content_header %}
                            <div class="sub-title">
                                {% block content_header_title %}
                                    <a href="{% url 'blog:index' %}" title="Home page" class="btn">
                                        <h2>ChernihVBlog</h2>
                                    </a>
                                {% endblock content_header_title %}
                                {% block content_header_icon %}
                                    <a href="{% url 'blog:contact' %}" title="Contact me">
                                        <i class="icon-envelope btn"></i>
                                    </a>
                                    {# login/logout #}
                                    {% if request.user.is_authenticated %}
                                        <a href="{% url 'blog:profile' %}" title="Profile">
                                            <i class="icon-user btn"></i>
                                        </a>
                                        <a href="{% url 'blog:create' %}" title="Create post">
                                            <i class="icon-pencil btn"></i>
                                        </a>
                                        {% if request.user.is_superuser %}
                                            <a href="{% url 'blog:new_question' %}" title="New questions">
                                                <i class="icon-question btn"></i>
                                            </a>
                                        {% endif %}
                                    {% else %}
                                        <a href="{% url 'blog:login' %}" title="Login">
                                            <i class="icon-login btn"></i>
                                        </a>
                                    {% endif %}
                                    <a href="{% url 'vue_js:index' %}">
                                        <i class="icon-anchor btn" title="Vue test page"></i>
                                    </a>

                                {% endblock content_header_icon %}
                            </div>
                        {% endblock content_header %}
                        <div class="col-md-12 content-page">

                            {% if messages %}
                                {% for message in messages %}
                                    <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                                        </button>
                                        <strong>{{ message }}</strong>
                                    </div>
                                {% endfor %}
                            {% endif %}

                            {% block page_content %}
                                {% block page_content_body %}
                                {% endblock page_content_body %}
                                {% block page_content_footer %}
                                    {% include 'blog/post/_load_button.html' %}
                                {% endblock page_content_footer %}
                            {% endblock page_content %}
                        </div>
                    </div>
                </div>

                {% block extend_content_block %}
                {% endblock extend_content_block %}

                {% block page_footer %}
                    <div class="col-md-12 page-body margin-top-50 footer">
                        <footer>
                            <ul class="menu-link">
                                {% block footer_navs_button %}
                                    <li><a href="{% url 'blog:index' %}">Home</a></li>
                                    <li><a href="{% url 'blog:contact' %}">Contact</a></li>
                                {% endblock footer_navs_button %}
                            </ul>

                            {% block page_footer_copyrigth %}
                                <div class="uipasta-credit">Developed by
                                    <a href="https://vk.com/id209493413" target="_blank">Черных Василий</a>
                                </div>
                                <a href="mailto:vasyachemax@yandex.ru">vasyachemax@yandex.ru</a>
                                <p>Powered by Django Framework</p>
                            {% endblock page_footer_copyrigth %}

                        </footer>
                    </div>
                {% endblock page_footer %}

            </div>
        </div>
    </div>

    {% block body_utils_arrow_to_top %}
        <a href="#" class="scroll-to-top"><i class="fa fa-long-arrow-up"></i></a>
    {% endblock body_utils_arrow_to_top %}

    {% block all_javascripts %}
        {% block main_javascripts %}
            <script type="text/javascript" src="{% static 'blog/js/jquery.min.js' %}"></script>
            <script type="text/javascript" src="{% static 'blog/js/plugin.js' %}"></script>
            <script type="text/javascript" src="{% static 'blog/js/scripts.js' %}"></script>
        {% endblock main_javascripts %}
        {% block custom_javascripts %}
        {% endblock custom_javascripts %}
    {% endblock all_javascripts %}

{% endblock body %}
</body>

</html>

django_demo/blog/templates/blog/post_create.html
{% extends 'blog/post_edit_block.html' %}
{% block page_title %}Create post{% endblock page_title %}
{% block post_title %}
    <div class="post-title">
        <h1>Create <span class="main-color">Post</span></h1>
    </div>
{% endblock post_title %}
{% block js_constants_extends %}
    <script>
        const ACTION_URL = '{% url 'blog:create' %}'
    </script>
{% endblock js_constants_extends %}

django_demo/blog/templates/blog/post_edit_block.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block page_content %}

    {% block post_title %}
    {% endblock post_title %}

    <div class="row">
        <div class="col-md-12">
            <div class="row">

                {% include 'blog/post/_post_form.html' with form=form image_form=image_form %}

            </div>
        </div>
    </div>

{% endblock page_content %}
{% block custom_javascripts %}
    {# Include constants for JS #}
    {% block js_constants_common %}
        <script>
            const CSRF_TOKEN = '{{ csrf_token }}';
            const POST_ID = '{{ form.instance.id }}';
            const PUBLISH_POST = '{% url 'blog:post_publish' form.instance.id %}';
            const CREATE_BLOCK_ACTION = '{% url 'blog:block_create' form.instance.id %}';
            const SAVE_BLOCK_ACTION = '{% url 'blog:block_save' form.instance.id %}';
            const DELETE_BLOCK_ACTION = '{% url 'blog:block_delete' form.instance.id %}';
        </script>
    {% endblock js_constants_common %}
    {% block js_constants_extends %}
    {% endblock js_constants_extends %}
    <script type="text/javascript" src="{% static 'blog/js/post_form.js' %}"></script>
{% endblock custom_javascripts %}

django_demo/blog/templates/blog/questions.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block page_content %}

    <div class="post-title margin-top-70">
        <h1>New <span class="main-color">Questions</span></h1>
    </div>

    {% if not questions %}
        <div class="alert alert-info">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>No new Questions</strong>
        </div>
    {% else %}

        {% for question in questions %}

            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">{{ question.email }} / {{ question.name }}</h3>
                    <a href="{% url 'blog:hide_question' question.id %}">Hide</a>
                </div>
                <div class="panel-body">
                    {{ question.question }}
                </div>
            </div>

        {% endfor %}

    {% endif %}


{% endblock page_content %}

django_demo/blog/templates/blog/user_detail.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block page_title %}User: {{ user.username }}{% endblock page_title %}
{% block page_content_body %}
    <div class="panel panel-default">
        <div class="panel-heading">Posts user: <a href="{% url 'blog:user' user.id %}">{{ user.username }}</a></div>
        <div class="panel-body">
            {% for post in user.post_set.all %}

                {% if not post.is_removed %}

                    {% include 'blog/post/_post_block.html' with post=post request=request truncatechars=True %}

                {% endif %}

            {% endfor %}
        </div>
    </div>
{% endblock page_content_body %}
{% block page_content_footer %}
    {% if user.post_set.count > 4 %}
        {% include 'blog/post/_load_button.html' %}
    {% endif %}
{% endblock page_content_footer %}

django_demo/blog/templates/blog/user_login.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block page_title %}User Login{% endblock page_title %}
{% block page_content %}

    <div class="post-title margin-top-70">
        <h1>User <span class="main-color">Login</span></h1>
    </div>

    <div class="row margin-top-30">
        <div class="col-md-12">

            <div class="row">

                <form method="post" action="{% url 'blog:login' %}">
                    {% csrf_token %}
                    <div class="col-sm-6">
                        <div class="form-group">
                            <input required type="text" id="{{ form.username.html_name }}"
                                   name="{{ form.username.html_name }}" class="form-control"
                                   placeholder="{{ form.username.label }}">
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            <input required type="password" id="{{ form.password.html_name }}"
                                   name="{{ form.password.html_name }}" class="form-control"
                                   placeholder="{{ form.password.label }}">
                        </div>
                    </div>

                    <div class="text-center">
                        <button type="submit" class="load-more-button">Enter</button>
                    </div>
                </form>

                <h3 class="text-center">You can <a href="{% url 'blog:registration' %}">Sign Up</a></h3>

            </div>
        </div>
    </div>

{% endblock page_content %}

django_demo/blog/templates/blog/user_profile.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block page_title %}Profile: {{ request.user }}{% endblock page_title %}
{% block page_content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            Username: <a class="main-color" href="{% url 'blog:user' request.user.id %}">{{ request.user.username }}</a>
            <br>
            Email: <a href="emailto:{{ request.user.email }}">{{ request.user.email }}</a>
        </div>
        <div class="panel-body">
            <h4><a href="{% url 'blog:user' request.user.id %}">My Posts</a></h4>
            <hr>
            <h4><a href="{% url 'blog:change_password' %}">Change Password</a></h4>
            <hr>
            <h4><a href="{% url 'blog:logout' %}">Logout</a></h4>
        </div>
    </div>
{% endblock page_content %}

django_demo/blog/templates/blog/user_registration.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block page_title %}User Registration{% endblock page_title %}
{% block page_content %}

    {% if message %}
        <div class="alert alert-warning">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <strong>{{ message }}</strong>
        </div>
    {% endif %}

    <div class="post-title margin-top-70">
        <h1>User <span class="main-color">Registration</span></h1>
    </div>

    <div class="row margin-top-30">
        <div class="col-md-12">

            <div class="row">

                <form method="post" action="{% url 'blog:registration' %}">
                    {% csrf_token %}
                    <div class="col-sm-6">
                        <div class="form-group">
                            <input required type="email" id="{{ form.email.html_name }}"
                                   name="{{ form.email.html_name }}" class="form-control"
                                   placeholder="{{ form.email.label }}">
                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            <input required type="text" id="{{ form.username.html_name }}"
                                   name="{{ form.username.html_name }}" class="form-control"
                                   placeholder="{{ form.username.label }}">
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group">
                            <input required type="password" id="{{ form.password.html_name }}"
                                   name="{{ form.password.html_name }}" class="form-control"
                                   placeholder="{{ form.password.label }}">
                        </div>
                    </div>

                    <div class="text-center">
                        <button type="submit" class="load-more-button">Send</button>
                    </div>
                </form>

            </div>
        </div>
    </div>

{% endblock page_content %}